# Generated by Django 5.2.5 on 2025-08-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price_regular',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price_vip',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=10),
        ),
    ]
