# Generated by Django 5.2.5 on 2025-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
