# Generated by Django 5.2.5 on 2025-08-17 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_booking_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
