# Generated by Django 5.2.5 on 2025-08-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_booking_expires_at_alter_booking_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='events.booking')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ticket')),
            ],
        ),
    ]
